ros_topics:
    camera_topic_left:  "/camera_1/sync_image_color"
    camera_topic_right:  "/camera_2/sync_image_color"
    lidar_topic: "/velodyne_points_synced"

image_select_col: 6
azimuth_angle_degrees:
    lower_val: -25
    upper_val: 25

depth_threshold_metres:
    lower_val: 0
    upper_val: 5

residual_thresh_ransac_metres: 0.15
min_points_ransac: 10
num_iter_ransac: 1000
num_samples_train: 15
camera_fps: 10
lidar_freq: 10
square_length_metres: 0.108
plot_cam_lidar_normals: true
plot_cam_lidar_plots: true
duration_sec: 120
